spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 200816
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.stdOutImpl
#        #设置MyBatis全局配置
        global-config:
          db_config:
#            table-prefix: t_
          id-type: auto

